name: Deploy to Linux Server

on:
  push:
    branches:
      - main  #
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd /var/www/TEST
          git fetch origin main  # Fetch latest changes
          git reset --hard origin/main
